2024-10-27 22:06:49,806 - app.main - INFO - request / endpoint!
2024-10-27 22:06:49,806 - app.main - DEBUG - debug
2024-10-27 22:07:38,564 - uvicorn.error - INFO - Shutting down
2024-10-27 22:07:38,665 - uvicorn.error - INFO - Waiting for application shutdown.
2024-10-27 22:07:38,665 - uvicorn.error - INFO - Application shutdown complete.
2024-10-27 22:07:38,665 - uvicorn.error - INFO - Finished server process [153055]
2024-10-27 22:07:38,679 - uvicorn.error - INFO - Stopping reloader process [152842]
2024-10-27 22:28:38,566 - uvicorn.error - INFO - Will watch for changes in these directories: ['/home/karel1ne/Documents/islameet-backend/ISLAMEET']
2024-10-27 22:28:38,566 - uvicorn.error - INFO - Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
2024-10-27 22:28:38,567 - uvicorn.error - INFO - Started reloader process [157281] using StatReload
2024-10-27 22:28:38,749 - asyncio - DEBUG - Using selector: EpollSelector
2024-10-27 22:28:39,777 - uvicorn.error - INFO - Started server process [157283]
2024-10-27 22:28:39,777 - uvicorn.error - INFO - Waiting for application startup.
2024-10-27 22:28:39,777 - uvicorn.error - INFO - Application startup complete.
2024-10-27 22:28:51,697 - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 327, in app
    content = await serialize_response(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 176, in serialize_response
    raise ResponseValidationError(
fastapi.exceptions.ResponseValidationError: 1 validation errors:
  {'type': 'model_attributes_type', 'loc': ('response',), 'msg': 'Input should be a valid dictionary or object to extract fields from', 'input': None}

2024-10-27 22:29:17,704 - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "ix_users_email"
DETAIL:  Key (email)=(string) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 214, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/concurrency.py", line 39, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2405, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 914, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/ISLAMEET/app/routers/user_router.py", line 13, in create_user
    return user_service.create_user(user)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/ISLAMEET/app/services/user_service.py", line 9, in create_user
    return self.user_repository.create_user(user)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/ISLAMEET/app/repositories/user_repository.py", line 12, in create_user
    self.db.commit()
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2028, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4352, in flush
    self._flush(objects)
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4487, in _flush
    with util.safe_reraise():
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4448, in _flush
    flush_context.execute()
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
             ^^^^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "ix_users_email"
DETAIL:  Key (email)=(string) already exists.

[SQL: INSERT INTO users (username, email, full_name) VALUES (%(username)s, %(email)s, %(full_name)s) RETURNING users.id]
[parameters: {'username': 'string', 'email': 'string', 'full_name': 'string'}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2024-10-27 22:29:31,719 - uvicorn.error - WARNING - StatReload detected changes in 'tests/test_users.py'. Reloading...
2024-10-27 22:29:31,733 - uvicorn.error - INFO - Shutting down
2024-10-27 22:29:31,834 - uvicorn.error - INFO - Waiting for application shutdown.
2024-10-27 22:29:31,834 - uvicorn.error - INFO - Application shutdown complete.
2024-10-27 22:29:31,834 - uvicorn.error - INFO - Finished server process [157283]
2024-10-27 22:29:32,052 - asyncio - DEBUG - Using selector: EpollSelector
2024-10-27 22:29:33,117 - uvicorn.error - INFO - Started server process [157515]
2024-10-27 22:29:33,117 - uvicorn.error - INFO - Waiting for application startup.
2024-10-27 22:29:33,117 - uvicorn.error - INFO - Application startup complete.
2024-10-27 22:31:31,904 - uvicorn.error - WARNING - StatReload detected changes in 'tests/test_users.py'. Reloading...
2024-10-27 22:31:31,957 - uvicorn.error - INFO - Shutting down
2024-10-27 22:31:32,058 - uvicorn.error - INFO - Waiting for application shutdown.
2024-10-27 22:31:32,058 - uvicorn.error - INFO - Application shutdown complete.
2024-10-27 22:31:32,058 - uvicorn.error - INFO - Finished server process [157515]
2024-10-27 22:31:32,263 - asyncio - DEBUG - Using selector: EpollSelector
2024-10-27 22:31:33,360 - uvicorn.error - INFO - Started server process [157785]
2024-10-27 22:31:33,360 - uvicorn.error - INFO - Waiting for application startup.
2024-10-27 22:31:33,360 - uvicorn.error - INFO - Application startup complete.
2024-10-27 22:31:38,656 - uvicorn.error - WARNING - StatReload detected changes in 'tests/test_users.py'. Reloading...
2024-10-27 22:31:38,678 - uvicorn.error - INFO - Shutting down
2024-10-27 22:31:38,779 - uvicorn.error - INFO - Waiting for application shutdown.
2024-10-27 22:31:38,779 - uvicorn.error - INFO - Application shutdown complete.
2024-10-27 22:31:38,779 - uvicorn.error - INFO - Finished server process [157785]
2024-10-27 22:31:38,981 - asyncio - DEBUG - Using selector: EpollSelector
2024-10-27 22:31:40,010 - uvicorn.error - INFO - Started server process [157817]
2024-10-27 22:31:40,010 - uvicorn.error - INFO - Waiting for application startup.
2024-10-27 22:31:40,011 - uvicorn.error - INFO - Application startup complete.
2024-10-27 22:32:33,503 - uvicorn.error - WARNING - StatReload detected changes in 'tests/test_users.py'. Reloading...
2024-10-27 22:32:33,568 - uvicorn.error - INFO - Shutting down
2024-10-27 22:32:33,669 - uvicorn.error - INFO - Waiting for application shutdown.
2024-10-27 22:32:33,669 - uvicorn.error - INFO - Application shutdown complete.
2024-10-27 22:32:33,669 - uvicorn.error - INFO - Finished server process [157817]
2024-10-27 22:32:33,863 - asyncio - DEBUG - Using selector: EpollSelector
2024-10-27 22:32:34,891 - uvicorn.error - INFO - Started server process [157912]
2024-10-27 22:32:34,891 - uvicorn.error - INFO - Waiting for application startup.
2024-10-27 22:32:34,892 - uvicorn.error - INFO - Application startup complete.
2024-10-27 22:34:25,102 - uvicorn.error - WARNING - StatReload detected changes in 'tests/test_users.py'. Reloading...
2024-10-27 22:34:25,114 - uvicorn.error - INFO - Shutting down
2024-10-27 22:34:25,215 - uvicorn.error - INFO - Waiting for application shutdown.
2024-10-27 22:34:25,215 - uvicorn.error - INFO - Application shutdown complete.
2024-10-27 22:34:25,216 - uvicorn.error - INFO - Finished server process [157912]
2024-10-27 22:34:25,418 - asyncio - DEBUG - Using selector: EpollSelector
2024-10-27 22:34:26,464 - uvicorn.error - INFO - Started server process [158178]
2024-10-27 22:34:26,465 - uvicorn.error - INFO - Waiting for application startup.
2024-10-27 22:34:26,465 - uvicorn.error - INFO - Application startup complete.
2024-10-27 22:35:13,838 - uvicorn.error - WARNING - StatReload detected changes in 'tests/test_users.py'. Reloading...
2024-10-27 22:35:13,902 - uvicorn.error - INFO - Shutting down
2024-10-27 22:35:14,003 - uvicorn.error - INFO - Waiting for application shutdown.
2024-10-27 22:35:14,003 - uvicorn.error - INFO - Application shutdown complete.
2024-10-27 22:35:14,003 - uvicorn.error - INFO - Finished server process [158178]
2024-10-27 22:35:14,198 - asyncio - DEBUG - Using selector: EpollSelector
2024-10-27 22:35:15,261 - uvicorn.error - INFO - Started server process [158301]
2024-10-27 22:35:15,262 - uvicorn.error - INFO - Waiting for application startup.
2024-10-27 22:35:15,262 - uvicorn.error - INFO - Application startup complete.
2024-10-28 07:25:42,344 - uvicorn.error - WARNING - StatReload detected changes in 'tests/test_users.py'. Reloading...
2024-10-28 07:25:42,443 - uvicorn.error - INFO - Shutting down
2024-10-28 07:25:42,582 - uvicorn.error - INFO - Waiting for application shutdown.
2024-10-28 07:25:42,599 - uvicorn.error - INFO - Application shutdown complete.
2024-10-28 07:25:42,602 - uvicorn.error - INFO - Finished server process [158301]
2024-10-28 07:25:42,870 - asyncio - DEBUG - Using selector: EpollSelector
2024-10-28 07:25:44,043 - uvicorn.error - INFO - Started server process [187180]
2024-10-28 07:25:44,043 - uvicorn.error - INFO - Waiting for application startup.
2024-10-28 07:25:44,044 - uvicorn.error - INFO - Application startup complete.
2024-10-28 07:26:53,856 - uvicorn.error - WARNING - StatReload detected changes in 'app/main.py'. Reloading...
2024-10-28 07:26:53,881 - uvicorn.error - INFO - Shutting down
2024-10-28 07:26:53,982 - uvicorn.error - INFO - Waiting for application shutdown.
2024-10-28 07:26:53,982 - uvicorn.error - INFO - Application shutdown complete.
2024-10-28 07:26:53,983 - uvicorn.error - INFO - Finished server process [187180]
2024-10-28 07:26:54,240 - asyncio - DEBUG - Using selector: EpollSelector
2024-10-28 07:26:55,461 - uvicorn.error - INFO - Started server process [187311]
2024-10-28 07:26:55,462 - uvicorn.error - INFO - Waiting for application startup.
2024-10-28 07:26:55,462 - uvicorn.error - INFO - Application startup complete.
2024-10-28 07:27:03,628 - uvicorn.error - WARNING - StatReload detected changes in 'app/main.py'. Reloading...
2024-10-28 07:27:03,691 - uvicorn.error - INFO - Shutting down
2024-10-28 07:27:03,792 - uvicorn.error - INFO - Waiting for application shutdown.
2024-10-28 07:27:03,792 - uvicorn.error - INFO - Application shutdown complete.
2024-10-28 07:27:03,792 - uvicorn.error - INFO - Finished server process [187311]
2024-10-28 07:27:04,024 - asyncio - DEBUG - Using selector: EpollSelector
2024-10-28 07:27:04,316 - uvicorn.error - WARNING - StatReload detected changes in 'app/main.py'. Reloading...
2024-10-28 07:27:05,496 - asyncio - DEBUG - Using selector: EpollSelector
2024-10-28 07:27:12,416 - uvicorn.error - WARNING - StatReload detected changes in 'app/main.py'. Reloading...
2024-10-28 07:27:12,608 - asyncio - DEBUG - Using selector: EpollSelector
2024-10-28 07:28:02,082 - uvicorn.error - WARNING - StatReload detected changes in 'app/models/user.py'. Reloading...
2024-10-28 07:28:02,315 - asyncio - DEBUG - Using selector: EpollSelector
2024-10-28 07:28:09,683 - uvicorn.error - WARNING - StatReload detected changes in 'app/models/user.py'. Reloading...
2024-10-28 07:28:09,882 - asyncio - DEBUG - Using selector: EpollSelector
2024-10-28 07:33:16,258 - uvicorn.error - INFO - Stopping reloader process [157281]
2024-10-28 07:33:17,640 - uvicorn.error - INFO - Will watch for changes in these directories: ['/home/karel1ne/Documents/islameet-backend/ISLAMEET']
2024-10-28 07:33:17,640 - uvicorn.error - INFO - Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
2024-10-28 07:33:17,640 - uvicorn.error - INFO - Started reloader process [188235] using StatReload
2024-10-28 07:33:17,839 - asyncio - DEBUG - Using selector: EpollSelector
2024-10-28 07:33:21,962 - uvicorn.error - INFO - Stopping reloader process [188235]
2024-10-28 07:33:30,640 - uvicorn.error - INFO - Will watch for changes in these directories: ['/home/karel1ne/Documents/islameet-backend/ISLAMEET']
2024-10-28 07:33:30,640 - uvicorn.error - INFO - Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
2024-10-28 07:33:30,640 - uvicorn.error - INFO - Started reloader process [188326] using StatReload
2024-10-28 07:33:30,831 - asyncio - DEBUG - Using selector: EpollSelector
2024-10-28 07:33:32,042 - uvicorn.error - INFO - Started server process [188328]
2024-10-28 07:33:32,042 - uvicorn.error - INFO - Waiting for application startup.
2024-10-28 07:33:32,043 - uvicorn.error - INFO - Application startup complete.
2024-10-28 07:33:35,154 - uvicorn.error - INFO - Shutting down
2024-10-28 07:33:35,254 - uvicorn.error - INFO - Waiting for application shutdown.
2024-10-28 07:33:35,255 - uvicorn.error - INFO - Application shutdown complete.
2024-10-28 07:33:35,255 - uvicorn.error - INFO - Finished server process [188328]
2024-10-28 07:33:35,271 - uvicorn.error - INFO - Stopping reloader process [188326]
2024-10-28 07:40:38,344 - uvicorn.error - INFO - Will watch for changes in these directories: ['/home/karel1ne/Documents/islameet-backend/ISLAMEET']
2024-10-28 07:40:38,344 - uvicorn.error - INFO - Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
2024-10-28 07:40:38,345 - uvicorn.error - INFO - Started reloader process [189644] using StatReload
2024-10-28 07:40:38,551 - asyncio - DEBUG - Using selector: EpollSelector
2024-10-28 07:40:39,716 - uvicorn.error - INFO - Started server process [189647]
2024-10-28 07:40:39,716 - uvicorn.error - INFO - Waiting for application startup.
2024-10-28 07:40:39,717 - uvicorn.error - INFO - Application startup complete.
2024-10-28 07:41:27,033 - app.main - INFO - request / endpoint!
2024-10-28 07:41:27,033 - app.main - DEBUG - debug
2024-10-28 07:41:44,662 - uvicorn.error - INFO - Shutting down
2024-10-28 07:41:44,763 - uvicorn.error - INFO - Waiting for application shutdown.
2024-10-28 07:41:44,763 - uvicorn.error - INFO - Application shutdown complete.
2024-10-28 07:41:44,763 - uvicorn.error - INFO - Finished server process [189647]
2024-10-28 07:41:44,780 - uvicorn.error - INFO - Stopping reloader process [189644]
2024-10-28 07:42:13,513 - uvicorn.error - INFO - Will watch for changes in these directories: ['/home/karel1ne/Documents/islameet-backend/ISLAMEET']
2024-10-28 07:42:13,514 - uvicorn.error - INFO - Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
2024-10-28 07:42:13,514 - uvicorn.error - INFO - Started reloader process [189971] using StatReload
2024-10-28 07:42:13,714 - asyncio - DEBUG - Using selector: EpollSelector
2024-10-28 07:42:14,782 - uvicorn.error - INFO - Started server process [189973]
2024-10-28 07:42:14,782 - uvicorn.error - INFO - Waiting for application startup.
2024-10-28 07:42:14,782 - uvicorn.error - INFO - Application startup complete.
2024-10-28 07:42:15,284 - uvicorn.error - INFO - Shutting down
2024-10-28 07:42:15,385 - uvicorn.error - INFO - Waiting for application shutdown.
2024-10-28 07:42:15,386 - uvicorn.error - INFO - Application shutdown complete.
2024-10-28 07:42:15,396 - uvicorn.error - INFO - Finished server process [189973]
2024-10-28 07:42:15,411 - uvicorn.error - INFO - Stopping reloader process [189971]
2024-10-28 07:48:42,342 - uvicorn.error - INFO - Will watch for changes in these directories: ['/home/karel1ne/Documents/islameet-backend/ISLAMEET']
2024-10-28 07:48:42,343 - uvicorn.error - INFO - Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
2024-10-28 07:48:42,353 - uvicorn.error - INFO - Started reloader process [191062] using StatReload
2024-10-28 07:48:42,543 - asyncio - DEBUG - Using selector: EpollSelector
2024-10-28 07:48:43,656 - uvicorn.error - INFO - Started server process [191064]
2024-10-28 07:48:43,656 - uvicorn.error - INFO - Waiting for application startup.
2024-10-28 07:48:43,657 - uvicorn.error - INFO - Application startup complete.
2024-10-28 07:48:55,844 - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedTable: relation "users" does not exist
LINE 1: INSERT INTO users (username, email, full_name) VALUES ('stri...
                    ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 214, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/concurrency.py", line 39, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2405, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 914, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/ISLAMEET/app/routers/user_router.py", line 13, in create_user
    return user_service.create_user(user)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/ISLAMEET/app/services/user_service.py", line 9, in create_user
    return self.user_repository.create_user(user)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/ISLAMEET/app/repositories/user_repository.py", line 12, in create_user
    self.db.commit()
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2028, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4352, in flush
    self._flush(objects)
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4487, in _flush
    with util.safe_reraise():
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4448, in _flush
    flush_context.execute()
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
             ^^^^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "users" does not exist
LINE 1: INSERT INTO users (username, email, full_name) VALUES ('stri...
                    ^

[SQL: INSERT INTO users (username, email, full_name) VALUES (%(username)s, %(email)s, %(full_name)s) RETURNING users.id]
[parameters: {'username': 'string', 'email': 'string', 'full_name': 'string'}]
(Background on this error at: https://sqlalche.me/e/20/f405)
2024-10-28 07:49:17,083 - uvicorn.error - INFO - Shutting down
2024-10-28 07:49:17,184 - uvicorn.error - INFO - Waiting for application shutdown.
2024-10-28 07:49:17,184 - uvicorn.error - INFO - Application shutdown complete.
2024-10-28 07:49:17,184 - uvicorn.error - INFO - Finished server process [191064]
2024-10-28 07:49:17,201 - uvicorn.error - INFO - Stopping reloader process [191062]
2024-10-28 07:57:52,132 - uvicorn.error - INFO - Will watch for changes in these directories: ['/home/karel1ne/Documents/islameet-backend/ISLAMEET']
2024-10-28 07:57:52,133 - uvicorn.error - INFO - Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
2024-10-28 07:57:52,133 - uvicorn.error - INFO - Started reloader process [192384] using StatReload
2024-10-28 07:57:52,324 - asyncio - DEBUG - Using selector: EpollSelector
2024-10-28 07:57:53,463 - uvicorn.error - INFO - Started server process [192386]
2024-10-28 07:57:53,463 - uvicorn.error - INFO - Waiting for application startup.
2024-10-28 07:57:53,463 - uvicorn.error - INFO - Application startup complete.
2024-10-28 07:58:53,387 - uvicorn.error - INFO - Shutting down
2024-10-28 07:58:53,489 - uvicorn.error - INFO - Waiting for application shutdown.
2024-10-28 07:58:53,489 - uvicorn.error - INFO - Application shutdown complete.
2024-10-28 07:58:53,489 - uvicorn.error - INFO - Finished server process [192386]
2024-10-28 07:58:53,505 - uvicorn.error - INFO - Stopping reloader process [192384]
2024-10-28 08:53:15,039 - uvicorn.error - INFO - Will watch for changes in these directories: ['/home/karel1ne/Documents/islameet-backend/ISLAMEET']
2024-10-28 08:53:15,040 - uvicorn.error - INFO - Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
2024-10-28 08:53:15,040 - uvicorn.error - INFO - Started reloader process [201025] using StatReload
2024-10-28 08:53:15,235 - asyncio - DEBUG - Using selector: EpollSelector
2024-10-28 08:53:16,318 - uvicorn.error - INFO - Started server process [201027]
2024-10-28 08:53:16,318 - uvicorn.error - INFO - Waiting for application startup.
2024-10-28 08:53:16,319 - uvicorn.error - INFO - Application startup complete.
2024-10-28 08:53:26,357 - uvicorn.error - INFO - Shutting down
2024-10-28 08:53:26,458 - uvicorn.error - INFO - Waiting for application shutdown.
2024-10-28 08:53:26,458 - uvicorn.error - INFO - Application shutdown complete.
2024-10-28 08:53:26,458 - uvicorn.error - INFO - Finished server process [201027]
2024-10-28 08:53:26,475 - uvicorn.error - INFO - Stopping reloader process [201025]
2024-10-28 08:56:53,739 - uvicorn.error - INFO - Will watch for changes in these directories: ['/home/karel1ne/Documents/islameet-backend/ISLAMEET']
2024-10-28 08:56:53,739 - uvicorn.error - INFO - Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
2024-10-28 08:56:53,776 - uvicorn.error - INFO - Started reloader process [201381] using StatReload
2024-10-28 08:56:53,967 - asyncio - DEBUG - Using selector: EpollSelector
2024-10-28 08:56:55,077 - uvicorn.error - INFO - Started server process [201383]
2024-10-28 08:56:55,078 - uvicorn.error - INFO - Waiting for application startup.
2024-10-28 08:56:55,078 - uvicorn.error - INFO - Application startup complete.
2024-10-28 08:57:03,153 - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedTable: relation "user_id_seq" does not exist
LINE 1: ... (id, username, email, full_name) VALUES (nextval('user_id_s...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 214, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/concurrency.py", line 39, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2405, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 914, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/ISLAMEET/app/routers/user_router.py", line 13, in create_user
    return user_service.create_user(user)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/ISLAMEET/app/services/user_service.py", line 9, in create_user
    return self.user_repository.create_user(user)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/ISLAMEET/app/repositories/user_repository.py", line 12, in create_user
    self.db.commit()
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2028, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4352, in flush
    self._flush(objects)
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4487, in _flush
    with util.safe_reraise():
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4448, in _flush
    flush_context.execute()
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
             ^^^^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "user_id_seq" does not exist
LINE 1: ... (id, username, email, full_name) VALUES (nextval('user_id_s...
                                                             ^

[SQL: INSERT INTO users (id, username, email, full_name) VALUES (nextval('user_id_seq'), %(username)s, %(email)s, %(full_name)s) RETURNING users.id]
[parameters: {'username': 'string', 'email': 'string', 'full_name': 'string'}]
(Background on this error at: https://sqlalche.me/e/20/f405)
2024-10-28 08:57:13,279 - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedTable: relation "user_id_seq" does not exist
LINE 1: ... (id, username, email, full_name) VALUES (nextval('user_id_s...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 214, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/starlette/concurrency.py", line 39, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2405, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 914, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/ISLAMEET/app/routers/user_router.py", line 13, in create_user
    return user_service.create_user(user)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/ISLAMEET/app/services/user_service.py", line 9, in create_user
    return self.user_repository.create_user(user)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/ISLAMEET/app/repositories/user_repository.py", line 12, in create_user
    self.db.commit()
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2028, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4352, in flush
    self._flush(objects)
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4487, in _flush
    with util.safe_reraise():
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4448, in _flush
    flush_context.execute()
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
             ^^^^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/karel1ne/Documents/islameet-backend/.venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "user_id_seq" does not exist
LINE 1: ... (id, username, email, full_name) VALUES (nextval('user_id_s...
                                                             ^

[SQL: INSERT INTO users (id, username, email, full_name) VALUES (nextval('user_id_seq'), %(username)s, %(email)s, %(full_name)s) RETURNING users.id]
[parameters: {'username': 'asdf asdf', 'email': '123dsafadsf', 'full_name': 'string'}]
(Background on this error at: https://sqlalche.me/e/20/f405)
2024-10-28 08:58:46,114 - uvicorn.error - WARNING - StatReload detected changes in 'app/models/user.py'. Reloading...
2024-10-28 08:58:46,189 - uvicorn.error - INFO - Shutting down
2024-10-28 08:58:46,289 - uvicorn.error - INFO - Waiting for application shutdown.
2024-10-28 08:58:46,290 - uvicorn.error - INFO - Application shutdown complete.
2024-10-28 08:58:46,290 - uvicorn.error - INFO - Finished server process [201383]
2024-10-28 08:58:46,514 - asyncio - DEBUG - Using selector: EpollSelector
2024-10-28 08:58:47,641 - uvicorn.error - INFO - Started server process [201557]
2024-10-28 08:58:47,641 - uvicorn.error - INFO - Waiting for application startup.
2024-10-28 08:58:47,641 - uvicorn.error - INFO - Application startup complete.
2024-10-28 08:58:49,248 - uvicorn.error - INFO - Shutting down
2024-10-28 08:58:49,349 - uvicorn.error - INFO - Waiting for application shutdown.
2024-10-28 08:58:49,349 - uvicorn.error - INFO - Application shutdown complete.
2024-10-28 08:58:49,350 - uvicorn.error - INFO - Finished server process [201557]
2024-10-28 08:58:49,363 - uvicorn.error - INFO - Stopping reloader process [201381]
2024-10-28 08:59:10,690 - uvicorn.error - INFO - Will watch for changes in these directories: ['/home/karel1ne/Documents/islameet-backend/ISLAMEET']
2024-10-28 08:59:10,690 - uvicorn.error - INFO - Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
2024-10-28 08:59:10,690 - uvicorn.error - INFO - Started reloader process [201656] using StatReload
2024-10-28 08:59:10,885 - asyncio - DEBUG - Using selector: EpollSelector
2024-10-28 08:59:12,118 - uvicorn.error - INFO - Started server process [201658]
2024-10-28 08:59:12,119 - uvicorn.error - INFO - Waiting for application startup.
2024-10-28 08:59:12,119 - uvicorn.error - INFO - Application startup complete.
2024-10-28 09:00:58,109 - uvicorn.error - INFO - Shutting down
2024-10-28 09:00:58,210 - uvicorn.error - INFO - Waiting for application shutdown.
2024-10-28 09:00:58,211 - uvicorn.error - INFO - Application shutdown complete.
2024-10-28 09:00:58,211 - uvicorn.error - INFO - Finished server process [201658]
2024-10-28 09:00:58,227 - uvicorn.error - INFO - Stopping reloader process [201656]
